# Site settings
email: dylan.p.huang@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Dylan Huang
description: Web enthusiast, Computer Engineer, Dog Lover
url: ""
twitter_username: https://twitter.com/dhuangster
default_img: https://scontent-iad3-1.xx.fbcdn.net/t31.0-8/13653050_1241431949208972_2082487078901060498_o.jpg

# Profile settings
name: Dylan Huang
profile_img: https://scontent-iad3-1.xx.fbcdn.net/t31.0-8/13653050_1241431949208972_2082487078901060498_o.jpg
profile: Web enthusiast, Computer Engineer, Dog Lover
social:
  github: https://github.com/dphuang2
  linkedin: https://www.linkedin.com/in/dphuang2

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

# Future posts
future: true
